{% set name = "pyxdf" %}
{% set version = "1.16.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 18908770b4847f9b223a97b2fd615fa62ac0cce305c08c407e71d7ec3ab6108b

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.5
    - pip
    - setuptools
    - setuptools_scm
  run:
    - python >=3.5
    - numpy
    - setuptools

test:
  imports:
    - pyxdf
    - pyxdf.pyxdf

about:
  home: https://github.com/xdf-modules/xdf-Python
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Python library for importing the Extensible Data Format (XDF)

extra:
  recipe-maintainers:
    - hoechenberger
