{% set name = "pyxdf" %}
{% set version = "1.16.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: aa0dfa4ed2d9ff5ec206d685144223822aefcd57eec940cd30f7cb0f16776e89

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.5
    - pip
    - setuptools
    - setuptools_scm
  run:
    - python >=3.5
    - numpy
    - setuptools

test:
  imports:
    - pyxdf
    - pyxdf.pyxdf

about:
  home: https://github.com/xdf-modules/xdf-Python
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Python library for importing the Extensible Data Format (XDF)'

extra:
  recipe-maintainers:
    - hoechenberger
