{% set name = "pyxdf" %}
{% set version = "1.16.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9c75db4e42b46bd8dbd69ff7ab190d7a461f55e28e2ff8279d5136d57f7849f6

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - setuptools_scm
  run:
    - python >={{ python_min }}
    - numpy
    - setuptools

test:
  requires:
    - python {{ python_min }}
  imports:
    - pyxdf
    - pyxdf.pyxdf

about:
  home: https://github.com/xdf-modules/xdf-Python
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Python library for importing the Extensible Data Format (XDF)

extra:
  recipe-maintainers:
    - hoechenberger
