{% set name = "pyxdf" %}
{% set version = "1.17.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9980c5506945632fcb27cca899e4db12b156d70fc31c703d3fdb2f0870dbaee9

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
    - hatch-vcs
  run:
    - python >={{ python_min }}
    - numpy >=2.0.2

test:
  requires:
    - python {{ python_min }}
  imports:
    - pyxdf
    - pyxdf.pyxdf

about:
  home: https://github.com/xdf-modules/xdf-Python
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Python library for importing the Extensible Data Format (XDF)

extra:
  recipe-maintainers:
    - hoechenberger
