travis:
  secure:
    BINSTAR_TOKEN: hcC+t3Oe1H4cnQ+q8uD6LLzg4LCjOHK6cvkeUVwveojhurHXQ+FXI1kUd/x/vxeuzMopSvMZyGdn1bN4jP4l1YUdPY0lDlJhG6Uapym1eQe+gzE5Peinv5QDQUeKAGj7EAaMi6sGbJ+52kssZg/x20BlJJ52LL46Z6LmxcoOtJiWYteAeRt1agmAEtUoqYAxpmIqEhqs4KhruHtuo0pYooO2kjB4SeeqCYU0/cxg0w90ieIY/jn77HdAzHjhKkY5oX01RikILHqsMsqDUuI2Sy0t30bY2orF2WExIWTMverxpiaZwMQ3m1PmVRblQIFPpuQF4VZkzq9GPQ+eRpEg25ypb8cXZ6WnQqos1h35Rx4J1TM1CPRXRmTvuQXSr4Sa852JlYZ++slRgD71E94c5fHwYVlM5/3hh7lJVi8vswW+PA6fLmKY9hyjI6pUjFgECmlfuqBdEiT7YEjRQQQlnxSXmn0EfxhyX9VrNoxwQerKSwZ5/Nw9YFH7SdxEWayoDSwN6BVv5Ui5aq2GeyCDovi+rAMe2xI1NtEOLUixKQchXB4nipzs5ignRKhSxSvVXzh9NZ4SJ39KiQ7XP+gIp03qkhmVogddKGafrdm3/9xmpr/WEZ7b8hnJDkL6Lz4+vcTqxFsLRzrIag3iQaulGZTnZTV9bylPecq3nLRLTYU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
