travis:
  secure:
    BINSTAR_TOKEN: bED0qvBoXHW6NEVYbJy62M3xHVKnDuVJjAx252+jxV1B+6UXi87NutnGRHkpT17+GApvUzIIw6V6ZxLj6uxcuTFOlY4Wd5Nm9nu3GS7V0nJSl3GmC6yoR+hMN345Abe7A0XdKw2r9eQ9nM8swVQ9AvKUgUPCwdD4AGE7WrZ9Nqr6QKHLDY90m3DW9vwVWGaL+UynBMGB2b32ulOyqxgU1Lc2L7w4L/3Q7oyOmgRxF3GGi26wOC/B9T+uTkhQmOznJIZO6Sz3BexLkl6oOW2Oqq7srbiMA6haHVa6pDzgmXh9215p5b/OT6/MDtqAeKjGo8LZ1ROdrFWw8N6WLPhGXO/3KEdm6FzRuJ/IXr1VMdUvCXOHlJFhm/xdtuMFLQ9FSzj2+ZzNydSqSVVEK8KGi7SzM631RikgmzQoSD8wWxhGab0gBJ0F7U2zAoKyncBfbalguhHV6XljEIKGJUm9GOSWRDNs2FPC3k9EBI0OXZgAxEqZw5yfxjY1AjjyKU12n0+w5cWXQYjvx6qW5PMlESUVR+Wdccc3+sRS2ZTEZA6GkbJ7WKldfu2yn+GWE6AHzpPA7PfYNmvXCAjH/J9K4xKLSqI6gPCc8IfQsNl35IwMkvWamDlT+HfdHdV1aZ8kD6GEc+dbcsQgmBu3nXAjykYCzQ+XWBr9ODsFmS4kJ9s=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
